### ISSUE TITLE
Sync Issues

### ISSUE THREAD

**Issue by skaman82** [Avamander/max7456#2]
I am using your library on a RC OSD project (https://github.com/skaman82/Pocket-Groundstation) and having some issues. I have a minimosd micro module (max7456 chip) between a 5.8 video RX and my video output. OSD is working fine (the voltage indicator with the black background in the following video). But when the video feed gets a bit poorer the OSD freaks out and flickers like this or sometime disappears for a second or two: 
https://www.youtube.com/watch?v=iRrj66cfb9g
Have you any idea how to make it stable?

**Comment by skaman82** [comment]
I also getting a black or grey background instead of static video. In this case its important to get static

**Comment by Avamander** [comment]
It's been a while since I last dealt with the chips, I'm sure the datasheet can help you more than I.
